import { useState } from "react";
import {
  X,
  Printer,
  Gear,
  Eye,
  Export,
  Spinner,
} from "@phosphor-icons/react";
import { useSlicerStore, formatDuration } from "@/stores/slicer-store";
import { usePrinterStore } from "@/stores/printer-store";
import { useEngineStore } from "@vcad/core";
import { useNotificationStore } from "@/stores/notification-store";
import { SlicerSettings } from "./SlicerSettings";
import { PrinterSelect } from "./PrinterSelect";
import { PrinterStatus } from "./PrinterStatus";
import { PrintPreview } from "./PrintPreview";

type Tab = "settings" | "preview" | "printer";

export function PrintPanel() {
  const [activeTab, setActiveTab] = useState<Tab>("settings");

  const closePrintPanel = useSlicerStore((s) => s.closePrintPanel);
  const isSlicing = useSlicerStore((s) => s.isSlicing);
  const setSlicing = useSlicerStore((s) => s.setSlicing);
  const stats = useSlicerStore((s) => s.stats);
  const setStats = useSlicerStore((s) => s.setStats);
  const sliceError = useSlicerStore((s) => s.sliceError);
  const setSliceError = useSlicerStore((s) => s.setSliceError);
  const setCurrentLayerPreview = useSlicerStore((s) => s.setCurrentLayerPreview);

  const selectedPrinter = usePrinterStore((s) => s.selectedPrinter);
  const connectionState = usePrinterStore((s) => s.connectionState);
  const printTemp = usePrinterStore((s) => s.printTemp);
  const bedTemp = usePrinterStore((s) => s.bedTemp);
  const setPrintTemp = usePrinterStore((s) => s.setPrintTemp);
  const setBedTemp = usePrinterStore((s) => s.setBedTemp);

  const scene = useEngineStore((s) => s.scene);
  const engine = useEngineStore((s) => s.engine);

  const addToast = useNotificationStore((s) => s.addToast);

  const hasMesh = scene?.parts && scene.parts.length > 0;

  async function handleSlice() {
    if (!engine || !scene?.parts?.length) {
      addToast("No model to slice", "error");
      return;
    }

    setSlicing(true);
    setSliceError(null);
    setStats(null);

    try {
      // Call the slicer WASM module
      // This would be the actual WASM call in production
      // For now, simulate slicing
      await new Promise((r) => setTimeout(r, 1500));

      // Mock stats
      const mockStats = {
        layerCount: 150,
        printTimeSeconds: 7200,
        filamentMm: 5000,
        filamentGrams: 23.4,
        boundsMin: [0, 0, 0] as [number, number, number],
        boundsMax: [50, 50, 30] as [number, number, number],
      };
      setStats(mockStats);

      // Mock layer preview for first layer
      setCurrentLayerPreview({
        z: 0.2,
        index: 0,
        outerPerimeters: [[[0, 0], [50, 0], [50, 50], [0, 50]]],
        innerPerimeters: [[[2, 2], [48, 2], [48, 48], [2, 48]]],
        infill: [
          [[5, 5], [45, 5]],
          [[5, 10], [45, 10]],
          [[5, 15], [45, 15]],
        ],
      });

      addToast("Slicing complete", "success");
      setActiveTab("preview");
    } catch (err) {
      const message = err instanceof Error ? err.message : "Slicing failed";
      setSliceError(message);
      addToast(message, "error");
    } finally {
      setSlicing(false);
    }
  }

  async function handleExportGcode() {
    if (!stats) return;

    try {
      // In production, this would call the WASM gcode generator
      const gcode = `; Generated by vcad
; Layers: ${stats.layerCount}
; Time: ${formatDuration(stats.printTimeSeconds)}
G28 ; Home
M104 S${printTemp} ; Set nozzle temp
M140 S${bedTemp} ; Set bed temp
; ... rest of gcode
`;

      // Download the file
      const blob = new Blob([gcode], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "print.gcode";
      a.click();
      URL.revokeObjectURL(url);

      addToast("G-code exported", "success");
    } catch (err) {
      addToast("Export failed", "error");
    }
  }

  async function handleStartPrint() {
    if (!selectedPrinter || connectionState !== "connected") {
      addToast("No printer connected", "error");
      return;
    }

    // In production, this would send the print job to the printer
    addToast("Print job sent to printer", "success");
  }

  return (
    <div className="fixed top-16 right-4 w-80 bg-surface border border-border rounded-lg shadow-lg z-30 flex flex-col max-h-[calc(100vh-5rem)]">
      {/* Header */}
      <div className="flex items-center justify-between p-3 border-b border-border">
        <div className="flex items-center gap-2">
          <Printer size={20} className="text-accent" />
          <span className="font-medium">Print</span>
        </div>
        <button
          onClick={closePrintPanel}
          className="p-1 hover:bg-hover rounded"
        >
          <X size={18} />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-border">
        <button
          onClick={() => setActiveTab("settings")}
          className={`flex-1 flex items-center justify-center gap-1 py-2 text-sm ${
            activeTab === "settings"
              ? "text-accent border-b-2 border-accent"
              : "text-text-muted hover:text-text"
          }`}
        >
          <Gear size={16} />
          Settings
        </button>
        <button
          onClick={() => setActiveTab("preview")}
          className={`flex-1 flex items-center justify-center gap-1 py-2 text-sm ${
            activeTab === "preview"
              ? "text-accent border-b-2 border-accent"
              : "text-text-muted hover:text-text"
          }`}
        >
          <Eye size={16} />
          Preview
        </button>
        <button
          onClick={() => setActiveTab("printer")}
          className={`flex-1 flex items-center justify-center gap-1 py-2 text-sm ${
            activeTab === "printer"
              ? "text-accent border-b-2 border-accent"
              : "text-text-muted hover:text-text"
          }`}
        >
          <Printer size={16} />
          Printer
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-3">
        {activeTab === "settings" && (
          <div className="space-y-4">
            <SlicerSettings />

            {/* Temperature settings */}
            <div className="border-t border-border pt-3">
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block text-xs text-text-muted mb-1">Nozzle °C</label>
                  <input
                    type="number"
                    value={printTemp}
                    onChange={(e) => setPrintTemp(parseInt(e.target.value) || 0)}
                    className="w-full h-8 px-2 text-sm bg-surface border border-border rounded text-text"
                  />
                </div>
                <div>
                  <label className="block text-xs text-text-muted mb-1">Bed °C</label>
                  <input
                    type="number"
                    value={bedTemp}
                    onChange={(e) => setBedTemp(parseInt(e.target.value) || 0)}
                    className="w-full h-8 px-2 text-sm bg-surface border border-border rounded text-text"
                  />
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === "preview" && (
          <div className="space-y-3">
            {stats ? (
              <>
                <PrintPreview />

                {/* Stats */}
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div className="bg-hover p-2 rounded">
                    <div className="text-text-muted text-xs">Layers</div>
                    <div className="font-mono">{stats.layerCount}</div>
                  </div>
                  <div className="bg-hover p-2 rounded">
                    <div className="text-text-muted text-xs">Time</div>
                    <div className="font-mono">{formatDuration(stats.printTimeSeconds)}</div>
                  </div>
                  <div className="bg-hover p-2 rounded">
                    <div className="text-text-muted text-xs">Filament</div>
                    <div className="font-mono">{stats.filamentGrams.toFixed(1)}g</div>
                  </div>
                  <div className="bg-hover p-2 rounded">
                    <div className="text-text-muted text-xs">Length</div>
                    <div className="font-mono">{(stats.filamentMm / 1000).toFixed(2)}m</div>
                  </div>
                </div>
              </>
            ) : (
              <div className="text-center py-8 text-text-muted">
                <Eye size={32} className="mx-auto mb-2 opacity-50" />
                <p className="text-sm">Click "Slice" to preview layers</p>
              </div>
            )}
          </div>
        )}

        {activeTab === "printer" && (
          <div className="space-y-3">
            <PrinterSelect />
            <PrinterStatus />
          </div>
        )}
      </div>

      {/* Footer actions */}
      <div className="p-3 border-t border-border space-y-2">
        {sliceError && (
          <div className="text-xs text-red-400 mb-2">{sliceError}</div>
        )}

        {/* Slice button */}
        <button
          onClick={handleSlice}
          disabled={!hasMesh || isSlicing}
          className="w-full flex items-center justify-center gap-2 py-2 bg-accent hover:bg-accent/90 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded font-medium"
        >
          {isSlicing ? (
            <>
              <Spinner className="animate-spin" size={18} />
              Slicing...
            </>
          ) : (
            <>
              <Eye size={18} />
              Slice
            </>
          )}
        </button>

        {/* Export / Print buttons */}
        {stats && (
          <div className="flex gap-2">
            <button
              onClick={handleExportGcode}
              className="flex-1 flex items-center justify-center gap-1 py-2 bg-hover hover:bg-border rounded text-sm"
            >
              <Export size={16} />
              Export G-code
            </button>
            <button
              onClick={handleStartPrint}
              disabled={!selectedPrinter || connectionState !== "connected"}
              className="flex-1 flex items-center justify-center gap-1 py-2 bg-green-600 hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded text-sm"
            >
              <Printer size={16} />
              Print
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
